export const ADD_NEW_BUCKET = "[BUCKET] ADD NEW BUCKET";
export const GET_ALL_BUCKETS = "[BUCKET] GET_ALL_BUCKETS";
export const UPDATE_BUCKET = "[BUCKET] UPDATE_BUCKET"
export const DELETE_BUCKET = "[BUCKET] DELETE_BUCKET"

